services:
  ubuntu:
    container_name: ubuntu
    image: ubuntu:test-task
    ports:
      - 80:80
      - 2222:22
    volumes:
      - ./ssh/id_ed25519.pub:/root/.ssh/authorized_keys
  ansible:
    container_name: ansible
    image: alpine/ansible
    volumes:
      - ./ssh:/root/.ssh
      - ../ansible/:/etc/ansible
    command: sh -c "apk add --no-cache py3-passlib && ansible-playbook /etc/ansible/playbook.yaml -i /etc/ansible/inventory/hosts/ubuntu.yaml"
    depends_on:
      - ubuntu